version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: easyessays-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: easyessays
    ports:
      - "5432:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data

volumes:
  pgdata-dev: